server.port=8082
spring.application.name=user-service

spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=DEBUG

# spring.profiles.active=local

# Annars ignoreras docker.properties
# Måste lägga default-profil i Run Configurations
# I Docker: sätts till "docker" via .env