# H�mtar v�rden fr�n milj�variabler injicerade av Docker Compose /EF
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&currentSchema=user_schema&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
internal.secret=${INTERNAL_SECRET}
auth-service.url=http://auth-service:8081
photo-service.url=http://photo-service:8086