services:
  birdnet:
    build:
      context: ./birdnet-service

  audio-service:
    build:
      context: .
      dockerfile: audio-service/Dockerfile
    ports:
      - "8087:8087"
    env_file:
      - .env
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      BIRDNET_URL: http://birdnet:5000
    depends_on:
      - birdnet

  # ROTERAS OCH LÄGGS I .ENV SEN!!
  geo-service:
    build:
      context: .
      dockerfile: geo-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=geo_schema&prepareThreshold=0"
      SPRING_DATASOURCE_USERNAME: postgres.tabpziwxnfwykijtykyv
      SPRING_DATASOURCE_PASSWORD: vazKy4-copgaq-qyspyz
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: docker


  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=user_schema&prepareThreshold=0"
      SPRING_DATASOURCE_USERNAME: postgres.tabpziwxnfwykijtykyv
      SPRING_DATASOURCE_PASSWORD: vazKy4-copgaq-qyspyz
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker

  # ROTERAS OCH LÄGGS I .ENV SEN!!
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0"
      SPRING_DATASOURCE_USERNAME: postgres.tabpziwxnfwykijtykyv
      SPRING_DATASOURCE_PASSWORD: vazKy4-copgaq-qyspyz
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
