server.port=8081
spring.application.name=auth-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect (behövdes ej dialekt /EF, testar utan)

spring.profiles.active=local

spring.security.oauth2.client.registration.google.scope=email,profile


