server.port=8084
spring.application.name=forum-service

spring.datasource.url=jdbc:postgresql://localhost:5432/winglog?currentSchema=forum_schema
spring.datasource.username=user_ef
spring.datasource.password=test_login_ef

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
