server.port=8085
spring.application.name=geo-service

spring.jpa.hibernate.ddl-auto=update

# spring.profiles.active=local
# Profil sätts via miljövariabel SPRING_PROFILES_ACTIVE /EF
# Lokalt i IntelliJ: sätt "local" i Run Configuration
# I Docker: sätts till "docker" via .env