server.port=8085
spring.application.name=geo-service

spring.datasource.url=jdbc:postgresql://localhost:5432/winglog?currentSchema=geo_schema
spring.datasource.username=user_ef
spring.datasource.password=test_login_ef

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
