server.port=8080
spring.application.name=api-gateway

#Detta sätter base/context-path till Gatway:en till "/gateway" /EF
server.servlet.context-path=/gateway
# Stäng av Gatewayens egen fil-tolkning så den skickar vidare filen orörd
spring.servlet.multipart.enabled=false
# Höj gränsen för hur mycket rådata (t.ex. bilder) som får passera, vet inte om detta funkar....
server.tomcat.max-http-form-post-size=5MB

# Plockat bort dessa och brutit ut till CorsConfig /EF
spring.profiles.active=local
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
