server.port=8080
spring.application.name=api-gateway

#Detta sätter base/context-path till Gatway:en till "/gateway" /EF
server.servlet.context-path=/gateway
# Tillåt trafik från Flutter Web (CORS-inställningar)
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

# Plockat bort dessa och brutit ut till CorsConfig /EF
spring.profiles.active=local
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
