auth-service.url=http://auth-service:8081
user-service.url=http://user-service:8082
geo-service.url=http://geo-service:8085
photo-service.url=http://photo-service:8086
audio-service.url=http://audio-service:8087
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
