server.port=8086
spring.application.name=photo-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.profiles.active=local

# Höjda gränser för kamerabilder /EF
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB